language: python
python:
  - 2.7
  - 3.3
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: 
  - coverage run --source=mhk_loader tests.py
after_success:
  - coveralls
